#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
# Web UI
location ~ ^/(api|buckets|config|explorer|dashboard|index|users) {
    proxy_pass http://127.0.0.1:__PORT_UI__;
    include proxy_params_no_auth;
}

location /assets/ {
    proxy_pass http://127.0.0.1:__PORT_UI__;
    include proxy_params_no_auth;
}

location /js/ {
    proxy_pass http://127.0.0.1:__PORT_UI__;
    include proxy_params_no_auth;
}
# S3 endpoint
location / {
            proxy_pass http://127.0.0.1:__PORT__;
            include proxy_params_no_auth;
            client_max_body_size 0;
        }
