#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_key=$(ynh_string_random --length=20)
admin_secret=$(ynh_string_random --length=40)
ynh_app_setting_set --app=$app --key=admin_key --value=$admin_key
ynh_app_setting_set --app=$app --key=admin_secret --value=$admin_secret

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_setup_source --dest_dir="$install_dir"
mkdir "$install_dir/$app.d"
ynh_config_add --template="gateway.conf" --destination="$install_dir/$app.d/$app.conf"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" 

yunohost service add "$app" --description="Versity S3 Gateway" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

chmod -R 700 "$data_dir/.iam"

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
