#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Upgrading source files..."
ynh_setup_source --dest_dir="$install_dir" --full_replace
mkdir "$install_dir/$app.d"

#=================================================
# UPDATE A CONFIG FILE
#=================================================

ynh_config_add --template="gateway.conf" --destination="$install_dir/$app.d/$app.conf"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" 

yunohost service add "$app" --description="Versity S3 Gateway" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

chmod -R 700 "$data_dir/.iam"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
